steps:
# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app:$SHORT_SHA',
    '.'
  ]

# Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app:$SHORT_SHA'
  ]

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - compute
  - instance-templates
  - create
  - app-template-$SHORT_SHA
  - --machine-type=e2-medium
  - --image-family=cos-stable
  - --image-project=cos-cloud
  - --metadata=startup-script=#! /bin/bash
    docker run -d -p 80:80 us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app:$SHORT_SHA


