steps:
  # 1. Build the Docker image using the current root directory (.)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/mohankrishnan-2489484/my-docker-repo/my-app:$SHORT_SHA', 
      '-t', 'us-central1-docker.pkg.dev/mohankrishnan-2489484/my-docker-repo/my-app:latest', 
      '.'
    ]

  # 2. Push the unique image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/mohankrishnan-2489484/my-docker-repo/my-app:$SHORT_SHA'
    ]

  # 3. Create a brand new Instance Template pointing to this exact new image version
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute instance-templates create my-app-template-$SHORT_SHA \
            --image-family=cos-stable \
            --image-project=cos-cloud \
            --service-account=mig-container-sa@mohankrishnan-2489484.iam.gserviceaccount.com \
            --scopes=https://www.googleapis.com/auth/cloud-platform \
            --region=us-central1 \
            --metadata=gce-container-declaration="spec:
          containers:
            - name: my-app
              image: 'us-central1-docker.pkg.dev/mohankrishnan-2489484/my-docker-repo/my-app:$SHORT_SHA'
              securityContext:
                privileged: false
          restartPolicy: Always"

  # 4. Trigger the rolling update on the MIG using the new template
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'compute', 'instance-groups', 'managed', 'rolling-action', 'start-update', 'my-mig',
      '--version=template=projects/mohankrishnan-2489484/regions/us-central1/instanceTemplates/my-app-template-$SHORT_SHA',
      '--region=us-central1'
    ]

images:
  - 'us-central1-docker.pkg.dev/mohankrishnan-2489484/my-docker-repo/my-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY